Encoding:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Max: 25

AbcSize:
  Max: 30

Documentation:
  Enabled: false

IndentationConsistency:
  Enabled: false

ModuleFunction:
  Enabled: false

RegexpLiteral:
  MaxSlashes: 0
